[2024-08-13T21:40:30.869+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.create_gcs_bucket manual__2024-08-13T21:25:03.348636+00:00 [queued]>
[2024-08-13T21:40:30.885+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.create_gcs_bucket manual__2024-08-13T21:25:03.348636+00:00 [queued]>
[2024-08-13T21:40:30.885+0000] {taskinstance.py:1359} INFO - Starting attempt 4 of 4
[2024-08-13T21:40:30.910+0000] {taskinstance.py:1380} INFO - Executing <Task(GCSCreateBucketOperator): create_gcs_bucket> on 2024-08-13 21:25:03.348636+00:00
[2024-08-13T21:40:30.920+0000] {standard_task_runner.py:57} INFO - Started process 23591 to run task
[2024-08-13T21:40:30.926+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_bigquery_etl', 'create_gcs_bucket', 'manual__2024-08-13T21:25:03.348636+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/extract_from_pg.py', '--cfg-path', '/tmp/tmprbctwo2i']
[2024-08-13T21:40:30.931+0000] {standard_task_runner.py:85} INFO - Job 522: Subtask create_gcs_bucket
[2024-08-13T21:40:31.018+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_to_bigquery_etl.create_gcs_bucket manual__2024-08-13T21:25:03.348636+00:00 [running]> on host d81d956e7878
[2024-08-13T21:40:31.184+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_bigquery_etl' AIRFLOW_CTX_TASK_ID='create_gcs_bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T21:25:03.348636+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-13T21:25:03.348636+00:00'
[2024-08-13T21:40:31.199+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-13T21:40:31.210+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-08-13T21:40:31.242+0000] {gcs.py:1066} INFO - Creating Bucket: stg-olist-ecommerce-dataset2; Location: europe-west2; Storage Class: MULTI_REGIONAL
[2024-08-13T21:40:34.463+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/gcs.py", line 149, in execute
    hook.create_bucket(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 467, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 1084, in create_bucket
    bucket.create(project=project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 972, in create
    client.create_bucket(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 961, in create_bucket
    api_response = self._post_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 625, in _post_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://storage.googleapis.com/storage/v1/b?project=utility-range-425622-c7&prettyPrint=false: Project 1068363464321 may not create storageClass MULTI_REGIONAL buckets with locationConstraint EUROPE-WEST2.
[2024-08-13T21:40:34.482+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=postgres_to_bigquery_etl, task_id=create_gcs_bucket, execution_date=20240813T212503, start_date=20240813T214030, end_date=20240813T214034
[2024-08-13T21:40:34.520+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 522 for task create_gcs_bucket (400 POST https://storage.googleapis.com/storage/v1/b?project=utility-range-425622-c7&prettyPrint=false: Project 1068363464321 may not create storageClass MULTI_REGIONAL buckets with locationConstraint EUROPE-WEST2.; 23591)
[2024-08-13T21:40:34.556+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-13T21:40:34.690+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
