[2024-08-14T17:49:55.701+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.create_gcs_bucket manual__2024-08-14T17:34:31.424328+00:00 [queued]>
[2024-08-14T17:49:55.716+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.create_gcs_bucket manual__2024-08-14T17:34:31.424328+00:00 [queued]>
[2024-08-14T17:49:55.717+0000] {taskinstance.py:1359} INFO - Starting attempt 4 of 4
[2024-08-14T17:49:55.742+0000] {taskinstance.py:1380} INFO - Executing <Task(GCSCreateBucketOperator): create_gcs_bucket> on 2024-08-14 17:34:31.424328+00:00
[2024-08-14T17:49:55.753+0000] {standard_task_runner.py:57} INFO - Started process 25486 to run task
[2024-08-14T17:49:55.760+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_bigquery_etl', 'create_gcs_bucket', 'manual__2024-08-14T17:34:31.424328+00:00', '--job-id', '526', '--raw', '--subdir', 'DAGS_FOLDER/extract_from_pg.py', '--cfg-path', '/tmp/tmp0bk_psfy']
[2024-08-14T17:49:55.764+0000] {standard_task_runner.py:85} INFO - Job 526: Subtask create_gcs_bucket
[2024-08-14T17:49:55.847+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_to_bigquery_etl.create_gcs_bucket manual__2024-08-14T17:34:31.424328+00:00 [running]> on host d81d956e7878
[2024-08-14T17:49:56.039+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_bigquery_etl' AIRFLOW_CTX_TASK_ID='create_gcs_bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T17:34:31.424328+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T17:34:31.424328+00:00'
[2024-08-14T17:49:56.055+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-14T17:49:56.072+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-08-14T17:49:56.151+0000] {gcs.py:1066} INFO - Creating Bucket: stg-olist-ecommerce-dataset2; Location: europe-west2; Storage Class: MULTI_REGIONAL
[2024-08-14T17:50:14.308+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/gcs.py", line 149, in execute
    hook.create_bucket(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 467, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 1084, in create_bucket
    bucket.create(project=project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/bucket.py", line 972, in create
    client.create_bucket(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 961, in create_bucket
    api_response = self._post_resource(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 625, in _post_resource
    return self._connection.api_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 72, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://storage.googleapis.com/storage/v1/b?project=utility-range-425622-c7&prettyPrint=false: Project 1068363464321 may not create storageClass MULTI_REGIONAL buckets with locationConstraint EUROPE-WEST2.
[2024-08-14T17:50:14.333+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=postgres_to_bigquery_etl, task_id=create_gcs_bucket, execution_date=20240814T173431, start_date=20240814T174955, end_date=20240814T175014
[2024-08-14T17:50:14.371+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 526 for task create_gcs_bucket (400 POST https://storage.googleapis.com/storage/v1/b?project=utility-range-425622-c7&prettyPrint=false: Project 1068363464321 may not create storageClass MULTI_REGIONAL buckets with locationConstraint EUROPE-WEST2.; 25486)
[2024-08-14T17:50:14.426+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-14T17:50:14.495+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
