[2024-08-17T18:47:58.450+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.create_bigquery_dataset manual__2024-08-17T18:47:43.984846+00:00 [queued]>
[2024-08-17T18:47:58.472+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_bigquery_etl.create_bigquery_dataset manual__2024-08-17T18:47:43.984846+00:00 [queued]>
[2024-08-17T18:47:58.472+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2024-08-17T18:47:58.502+0000] {taskinstance.py:1380} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_bigquery_dataset> on 2024-08-17 18:47:43.984846+00:00
[2024-08-17T18:47:58.512+0000] {standard_task_runner.py:57} INFO - Started process 214 to run task
[2024-08-17T18:47:58.518+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_bigquery_etl', 'create_bigquery_dataset', 'manual__2024-08-17T18:47:43.984846+00:00', '--job-id', '728', '--raw', '--subdir', 'DAGS_FOLDER/extract_from_pg.py', '--cfg-path', '/tmp/tmp6w31bqnv']
[2024-08-17T18:47:58.523+0000] {standard_task_runner.py:85} INFO - Job 728: Subtask create_bigquery_dataset
[2024-08-17T18:47:58.638+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_to_bigquery_etl.create_bigquery_dataset manual__2024-08-17T18:47:43.984846+00:00 [running]> on host c04129f4379c
[2024-08-17T18:47:58.829+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_bigquery_etl' AIRFLOW_CTX_TASK_ID='create_bigquery_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T18:47:43.984846+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T18:47:43.984846+00:00'
[2024-08-17T18:47:58.843+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-08-17T18:47:58.854+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-08-17T18:47:58.855+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value olist_ecommerce_dataset.
[2024-08-17T18:47:58.855+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value utility-range-425622-c7.
[2024-08-17T18:47:58.855+0000] {bigquery.py:481} INFO - Creating dataset: olist_ecommerce_dataset in project: utility-range-425622-c7 
[2024-08-17T18:48:01.549+0000] {bigquery.py:485} INFO - Dataset created successfully.
[2024-08-17T18:48:01.629+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=postgres_to_bigquery_etl, task_id=create_bigquery_dataset, execution_date=20240817T184743, start_date=20240817T184758, end_date=20240817T184801
[2024-08-17T18:48:01.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-17T18:48:01.756+0000] {taskinstance.py:2776} INFO - 9 downstream tasks scheduled from follow-on schedule check
